### ISSUE TITLE
Include thirdparty libraries as submodules

### ISSUE THREAD

**Issue by feliwir** [WolfireGames/overgrowth#19] opened 2022-04-25 12:46 UTC
Hello,
would it be welcome if i include thirdparty libraries as submodules? 
It makes managing & versioning a lot simpler and reduces the overall size of the repository. Of course this is only viable if there weren't any customizations done to the libraries.

Most projects (in their unmodified form) can just be compiled by using `add_subdirectory` - this would probably require updating a few of the dependencies.

**Comment by autious** [comment] 2022-04-25 12:49
There's already a discussion related to this here https://github.com/WolfireGames/overgrowth/issues/15, i suggest adding to that discussion.

**Comment by Conan-Kudo** [comment] 2022-04-25 13:00
Duplicate of #15

**Closed by Conan-Kudo** 2022-04-25 13:00 UTC
